### ISSUE TITLE
NEWSセクション(PC)レイアウト崩れ

### ISSUE THREAD

**Issue by totzyuta** [totzyuta/gaudiy#14]
NEWSセクションの上の四角の部分がレイアウト崩れしてました確認お願いします 🙏 🙏 

![screen shot 2018-11-25 at 11 43 51 pm](https://user-images.githubusercontent.com/3541156/48980426-00caea80-f10c-11e8-9244-45f06a544fab.png)

**Comment by mtsmtyuta** [comment]
対応しました！
