### ISSUE TITLE
ブラウザ幅が小さくなった時に全体の幅がくずれてしまう現象なおしたい

### ISSUE THREAD

**Issue by totzyuta** [totzyuta/gaudiy#15]
![screen shot 2018-11-26 at 12 35 48 am](https://user-images.githubusercontent.com/3541156/48980983-4fc84e00-f113-11e8-95f7-a45754eaec5d.png)

**Comment by mtsmtyuta** [comment]
対応しました！チェックお願いします。

**Comment by totzyuta** [comment]
ありがとう！いい感じになってた👌
